---
config:
  locations:
    storage: $HOME/.am
    cache: $HOME/.cache/am
    links:
      binary: $HOME/.local/bin
      man: $HOME/.local/share/man
      bash_completion: $HOME/.bash_completion.d
      zsh_completion: $HOME/.zsh/completions
      fish_completion: $HOME/.config/fish/completions
  assets:
    owner: $USER
    group: $USER
    mode: "0755"

groups:
  - name: hurl
    versions:
      - value: "6.0.0"
        current: true
    remotes:
      - type: github
        owner: Orange-OpenSource
        repo: hurl
        tag: "{{ .version }}"
        assets:
          - id: linux-all
            name: "hurl-{{ .version }}-x86_64-unknown-linux-gnu.tar.gz"
    integrity:
      - type: sha256
        asset: linux-all
        references:
          - version: "6.0.0"
            value: 20bed7a6b76060f6577d1f5dd1aa4c6b9e4462d9700b53c86aa641fe38ea7db1
    targets:
      - asset: linux-all
        strip-components: 1
        permissions:
          - path: man
            recursive: true
            mode: "0644"
          - path: completions
            mode: "0644"
          - path: bin/*
    links:
      - target: '^bin\/(?P<name>hurl\w*)$'
        regex: true
        type: binary
        name: "{{ .name }}"
      - target: '^man\/(?P<name>man\d)$'
        regex: true
        type: man
        name: "{{ .name }}"
      - target: '^completions\/(?P<name>\_hurl\w*)$'
        regex: true
        type: zsh_completion
        name: "{{ .name }}"

  - name: zookeeper
    versions:
      - value: "3.9.3"
        current: true
      - value: "3.9.2"
        current: true
    remotes:
      - type: http
        address: https://dlcdn.apache.org/zookeeper/
        assets:
          - id: zk
            location: zookeeper-{{ .version }}/apache-zookeeper-{{ .version }}-bin.tar.gz
    integrity:
      - type: sha512
        asset: zk
        references:
          - version: "3.9.3"
            value: d44d870c1691662efbf1a8baf1859c901b820dc5ff163b36e81beb27b6fbf3cd31b5f1f075697edaaf6d3e7a4cb0cc92f924dcff64b294ef13d535589bdaf143
          - version: "3.9.2"
            value: 2b5ae02d618a27ca8cd54924855d5344263b7d9dee760181f9d66bafa9230324d2ad31786895f0654c969dc38d4a3d0077f74cc376b58b5fa2fb94beb1ab445f
    targets:
      - asset: zk
        permissions:
          - path: bin/*.sh
            # regex: true
    links:
      - target: '^bin\/(?P<name>\w+\.sh)$'
        regex: true
        type: binary
        name: "{{ .name }}"

  - name: terraform
    versions:
      - value: "1.11.1"
        current: true
    remotes:
      - type: hashicorp
        repo: terraform
        version: "{{ .version }}"
        assets:
          - id: linux-amd64
            name: "terraform_{{ .version }}_linux_amd64.zip"
    integrity:
      - type: sha256
        asset: linux-amd64
        references:
          - version: "1.11.1"
            value: 1af58f77958186227bce9ae4d9b08e004fb0902c7a6bdc813cdbab88739f9316
    targets:
      - asset: linux-amd64
        permissions:
          - path: terraform
    links:
      - target: terraform
        name: terraform
